### PR TITLE
Database ms

### PR DESCRIPTION
**Pull request by Suganya31**
In this pull request, update and query a named graph functionality as well as a method to process sparql query is added  to database microservice. Also we add a method to get the name of all graphs from the database. According to search group request the updateAutoIndex method added to send a copy of all triples in database to AutoIndex.

### CODE REVIEW

**Comment by prasanthhs** [comment]
@Suganya31 Can you please fix the Codacy issues before merge since @idreestahir already has many issues left. There are only 4 issues in total so it won't take much time. Click on details next to Codacy and it will tell what those issues are and what would be the proposed changes.

**Comment by Suganya31** [comment]
@prasanthhs Will you be considering the solutions provided by @KHaack or should we disable the test?

**Comment by prasanthhs** [comment]
@Suganya31 it is fine to disable the tests for now. Probably, the permanent solution should be to start fuseki from code, or one of the two options provided by @KHaack so that travis will not always show compilation error.

Example of starting Fuseki from Code: https://github.com/apache/jena/blob/master/jena-fuseki2/jena-fuseki-embedded/src/test/java/org/apache/jena/fuseki/embedded/TestEmbeddedFuseki.java

**Comment by sepidetari** [comment]
@KHaack after disabling tests all the checks have passed. configuration in Travis still needed or its fine?

**Comment by KHaack** [comment]
currently we dont want to make integration tests on travis

**Pull request merged**
