### PR TITLE
Chatbot junit test

### PR DESCRIPTION
**Pull request by Juzerhk**
Chabot is now able to handle "bye" and other single word requests.

chatbot_bye

### CODE REVIEW

**Comment by Juzerhk** [comment]
All checks passed successfully. Code can be merged now

**Comment by guru5590** [comment]
@Juzerhk , Thanks for making the changes and sending it for review. Please note from the next time. Try to create a branch for the fix, rather than making the changes on an older branch. In this way, all of us can infer, why the branch was created in the first place. Also saves you from maintaining older branches

**Comment by guru5590** [comment]
@Juzerhk I just put some debug messages to view the code logs, it looks like a string message is treated as a valid Json. Can you please check why is this issue occuring. Attaching the screenshot for your reference.

screen shot 2018-05-08 at 21 33 38

**Comment by guru5590** [comment]
Merging the pull request as this fixes this issue, @Juzerhk, But the problem with your fix is maskes the real issue with the library used.

**Pull request merged**
