### PR TITLE
Search

### PR DESCRIPTION
**Pull request by guru5590**
This commit, includes the chatbot functionality into main sask project. 

Features of the chatbot:

a) A simple UI based on Jquery (TODO: integrate this UI with the overall UI module of the sask project
b) Chatbot supports QA systems via integration with HAWK framework
c) Greeting features are supported by including the custom Rivescripts and few parts of the ELISA framework.

As with the other modules, this chatbot module also builds on top of Eureka server.

### CODE REVIEW

**Comment by divyasrinivasan1986** [comment]
Updated pom xml file for Java 9 dependancy problem.

**Comment by RicardoUsbeck** [comment]
After starting the latest commit, I see all 4 ms running:
image

But port 9090 is gone 
image

And port 8080 doesn't show the UI
image

Please fix. @KHaack @AndreSonntag do you agree that the UI is not reachable.

**Comment by prasanthhs** [comment]
@RicardoUsbeck  UI is displayed on ip:9090/index.html. This is the current mapping. (8080 has been removed with our commit due to way too many predictable clashes on default port).

**Comment by RicardoUsbeck** [comment]
Normally, this push request would not have been merged due to #12, #9  but we move that to a later release. @KHaack @AndreSonntag @prasanthhs please consider creating a QA team (can be one dedicated person or multiple) to check pull request for such issues. The QA team would get permission for merging.

**Pull request merged**
