### PR TITLE
Ui workspace repo

### PR DESCRIPTION
**Pull request by KHaack**
Contains the nearly finished ui and repo stuff. currently located on the "ui prototype" page (http://localhost:9090/uiprototype.html).

To run this: start eureka, the hadoop docker, the repo-ms, the webclient-ms and one or more extractors.

See: https://github.com/dice-group/sask/wiki/Hadoop
and https://github.com/dice-group/sask/blob/master/README.md

If all microservices are running, but are not available in the application:
Wait, till the webclient pulled a refreshed list.

Currently discovered microservices: http://localhost:9090/status.html

### CODE REVIEW

**Comment by RicardoUsbeck** [comment]
For the reviewers, show it works by posting individual screenshots.

**Comment by KHaack** [comment]
Feature screenshots on our google drive:
https://drive.google.com/drive/folders/19OmqurgfpnMclco_UHYVXEWRrb7a72VX?usp=sharing

Upload a single file with the ui to hadoop:
01_Upload_single.png

Upload multiple files with the ui to hadoop:
01_Upload_multi.png

Create hierarchical folder structure in the repo:
08_repo_folder.png

Create workflows:
03_Workflow_create.png

Save the workflows:
04_Workflow_saved.png

Load the saved workflows:
05_Workflow_load.png

Workflow undo/redo:
06_Workflow_undo.png

See the dynamic statuc for the microservices:
07_Status.png

See the uplaoded files in hadoop:
Hadoop.png

**Comment by prasanthhs** [comment]
@KHaack Can you please briefly tell us what we should be checking? For example for extraction pipeline, what should be a good  input file etc? 

@RicardoUsbeck @KHaack Can we write and maintain a script for starting micro services? There are way too many to start manually. Integration with starting Hadoop would also be nice if possible. I have attached a sample in shell script for your reference.  

[script.sh.txt](https://github.com/dice-group/sask/files/1815595/script.sh.txt)

Lastly, for consistency, Can you please rename package "OpenIE-ms" to "openie-ms"?

**Comment by prasanthhs** [comment]
@KHaack When i loaded UIPrototype.html as you mentioned in procedure, I also get some errors on repo-ms. On checking status, i saw repo not listed as a micro service and I tried to manually start repo-ms it since it wasn't compiled as a part of main pom.xml (not a module , similar problem with dbpedia-ms but that compiles well?). 

UI ERROR: <<Discoverer.js:26 no microservice with the type 'repo' discovered.>>

repo-ms error:
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project repo-ms: Compilation failure: Compilation failure:
[ERROR] /home/pgadmin/Prashanth/sask/repo-ms/src/main/java/org/dice_research/sask/repo_ms/WebHDFSUriBuilder.java:[5,36] package org.apache.http.client.utils does not exist
[ERROR] /home/pgadmin/Prashanth/sask/repo-ms/src/main/java/org/dice_research/sask/repo_ms/WebHDFSUriBuilder.java:[24,17] cannot find symbol
[ERROR] symbol:   class URIBuilder
[ERROR] location: class org.dice_research.sask.repo_ms.WebHDFSUriBuilder
[ERROR] /home/pgadmin/Prashanth/sask/repo-ms/src/main/java/org/dice_research/sask/repo_ms/WebHDFSUriBuilder.java:[24,42] cannot find symbol
[ERROR] symbol:   class URIBuilder
[ERROR] location: class org.dice_research.sask.repo_ms.WebHDFSUriBuilder

Environment is the virtual machine which @RicardoUsbeck assigned to our team under folder Prashanth in root. Source code i took from ui-workspace-repo.

**Comment by KHaack** [comment]
@prasanthhs i think for the error: clean and build. Or clean the mvn repo

**Comment by KHaack** [comment]
@prasanthhs if you want to check the functions from the screens.

**Comment by KHaack** [comment]
@prasanthhs a start script is on the task list since december

**Comment by prasanthhs** [comment]
@KHaack Nope, same compilation error on "mvn clean package" .

Here are my main review comments so far.

1 . Add dbpedia-ms and repo-ms to parent pom so that mvn clean package will compile everything on parent level. dbpedia-ms pom.xml also requires a small change, its name is provided as discovery-client in pom.xml.

2. Compile error on package of repo-ms. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project repo-ms: Compilation failure: Compilation failure:
[ERROR] /home/pgadmin/Prashanth/sask/repo-ms/src/main/java/org/dice_research/sask/repo_ms/WebHDFSUriBuilder.java:[5,36] package org.apache.http.client.utils does not exist
[ERROR] /home/pgadmin/Prashanth/sask/repo-ms/src/main/java/org/dice_research/sask/repo_ms/WebHDFSUriBuilder.java:[24,17] cannot find symbol
[ERROR] symbol:   class URIBuilder
[ERROR] location: class org.dice_research.sask.repo_ms.WebHDFSUriBuilder

3. OpenIE-ms -> openie-ms

**Comment by prasanthhs** [comment]
@KHaack I got the functionality, that seems straightforward from both the sample UI as well as your screenshots. I wanted to check about the Input file you have extracted in your example.

**Comment by KHaack** [comment]
@prasanthhs 
1. dbpedia-ms was merged manually and will be not used in this version. see #23. and the module name is currently not important.

2. I think you're working on a dirty workspace. Clean and build: https://stackoverflow.com/questions/11568855/why-cant-eclipse-resolve-class-in-same-package

3. [...]and the module name is currently not important. naming convention should be discussed later in a meeting, not in the comment section of a pull request.

**Comment by KHaack** [comment]
@prasanthhs 
"I wanted to check about the Input file you have extracted in your example.": which example? extraction and execute a workflow is part of the executer branch. see https://github.com/dice-group/sask/tree/executer-ms

**Comment by prasanthhs** [comment]
@KHaack 
1. About dbpedia, I just mentioned as an extra observation. It is up to you when you want to add. But repo-ms  is used in your current UI and so should be in parent pom and compilable at parent level.  Similarly module names are a generally followed norm(all lower case letters) to avoid clashing with class names. Again, a low priority observation but a code review comment nonetheless. 

2. Please read my comments completely first before guessing what my procedural mistake is. 
First of all, I use the university VM, Second i use command Line and not eclipse and lastly i downloaded the latest code from repository using git clone. 

<<<<
Environment is the virtual machine which @RicardoUsbeck assigned to our team under folder Prashanth in root. Source code i took from ui-workspace-repo
>>>>>

If you require further information, let me know.

**Comment by prasanthhs** [comment]
@KHaack Thank you. The example (i was referring to) were the one used in your snapshots. Since you mentioned that file doesn't matter, let me try with some random txt file.

**Comment by prasanthhs** [comment]
@KHaack Can you please add org.apache.httpcomponents  as a dependancy to pom.xml ? This would solve the compilation error of repo-ms.

**Comment by KHaack** [comment]
@prasanthhs please write your environment specifications down... on all our test systems every thing is running. `org.apache.httpcomponents` should be present. And sorry that i tried to help you

**Comment by prasanthhs** [comment]
@KHaack Does your environment have Java 9? The VM uses latest Java9 environment and you maybe(?) are on an older version of Java  which is probably why it doesn't cause any error for you. I am not sure about it since i do not know how your env is. Other than that, I use only command line for running code on the ubuntu VM and access of UI is using Remote URL from my web browser.
Adding httpclient explicitly as dependency to pom.xml solves this problem otherwise compilation error will be present.

**Comment by KHaack** [comment]
@prasanthhs If you want to presuppose a specific environment, please specify it exactly. We all use Java 9 only. And this specification is a group decision. But that should be discussed in a meeting. A decision could be whether we want to use Orcale or a Open solution. Maybe your environment use another Java. Let me help you and give me your specifications.

**Comment by prasanthhs** [comment]
@KHaack As i mentioned before, I use University VM which @RicardoUsbeck has provided to both teams to access. And the Java version is as below:

java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

If you require other details, please let me know.

**Comment by KHaack** [comment]
Ok, not the latest java, but the same we use.

**Pull request closed without merging**
