### PR TITLE
Ansible Scripts Integration with Travis

### PR DESCRIPTION
**Pull request by guru5590**
1) Integrated with codecov for code coverage stats.
2) The deployment scripts are called as part of the travis continuous integration. The ansible playbooks for create docker image and deploying them are triggered only on the master branch. This can be changed easily based on parameters.

P.S: Sorry for many commits, coz it was an experimenting phase which could have been tested only when pushed to github.

### CODE REVIEW

**Comment by prasanthhs** [comment]
@guru5590 There is a deploy_rsa.enc file which is of type binary.  
/root/sask_hadoop_settings.sh-> Where is this file?

**Comment by guru5590** [comment]
@prasanthhs, sask_hadoop_settings.sh from the repository will be copied on to the host system where hadoop will be deployed and its volume mounted into the docker container. It was missed out, I added it in a new commit.

deploy_rsa.enc travis encrypted private key file, which will be used to ssh into the host where the docker containers will be deployed. This file is used to create a trust between the travis ci with the node which is used for deployment.

**Comment by prasanthhs** [comment]
@guru5590 Seems OK. But @RicardoUsbeck mentioned, please update ReadMe and wiki, Wiki for the code coverage change you have done and if any changes are required to the demo put on wiki/playbook Read Me, then please change them as well.

**Comment by guru5590** [comment]
@prasanthhs , I have captured the codecov details in a wiki page... Can I go ahead and merge this request?

**Pull request merged**
