### PR TITLE
Chat integration

### PR DESCRIPTION
**Pull request by KHaack**
In this branch we are integrate the chat into the ui. The user is now able to chat while working on the workspace. The size of the chat or the workspace can be changed with the button at the top right corner. And if the chatbot returns a big answer, the chat will be automatically maximized.

grafik
grafik

We also introduced the maven profiles ```windows``` and ```linux```. So logback can be configured for the operating system. In addition we added the log level properties to the ```pom.xml```. The level is currently on ```WARN```. 

The rest is code styling.

Please note: there is currently no running qa system

The run command is:
```
mvn clean spring-boot:run -P windows
```
or
```
mvn clean spring-boot:run -P linux
```

### CODE REVIEW

**Comment by KHaack** [comment]
Jep, some are eligible, others are not.
I make one more styling commit :)

**Comment by prasanthhs** [comment]
@KHaack The feedback implementation by @divyasrinivasan1986 is overwritten by this change. We don't get feedback prompt in UI anymore.

**Comment by KHaack** [comment]
i think it is a merge error, you only get the Feedback form if it is a qa answer. ill fix it :)

**Comment by KHaack** [comment]
done for now
grafik

any other improvements?

**Comment by prasanthhs** [comment]
@KHaack We can merge if its ok. I already checked on your PC and its fine.

**Pull request merged**
