### PR TITLE
Base code of Sessa web service.

### PR DESCRIPTION
**Pull request by prasanthhs**
@Muzammil1234's Sessa code put into a new branch due to search being an older branch with code differences from master.  

* Some timeout error and load balancing problem needs to be checked.

### CODE REVIEW

**Comment by RicardoUsbeck** [comment]
image
How can I start the SESSA app to test the that it runs and actually does what it is supposed to do?

**Comment by prasanthhs** [comment]
Sessa can be started by normal procedure(@Muzammil1234  checked in some code to Sessa WS under sessa_webservice branch). Other option is that sessa running in our vm as a docker,the same can be used to check.

**Comment by RicardoUsbeck** [comment]
After starting SESSA locally, I get the following error on command line after entering "Berlin" into the chat interface, see file.
[log_sessa_18.12.2017.txt](https://github.com/dice-group/sask/files/1568704/log_sessa_18.12.2017.txt)

**Comment by prasanthhs** [comment]
@RicardoUsbeck Couple of things : First chatbot has to be started before web client can run(Because zuul internally gets the port of chatbot from eureka during run time). Hence the below error 

Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: chatbot

Sometimes, we get either timeout error or load balance related error when using MacBook terminal Currently we have to check as to why it happens. The only workaround for this issue we have at the moment is to open a new terminal and restart web client after chatbot is running.

**Comment by guru5590** [comment]
Hi Ricardo,

We have setup a docker registry in our VM but with unsigned certificates.

Add the below snippet to /etc/docker/demon.json and restart the docker
service

{
  "insecure-registries" : ["project-group-search-
extraction.cs.uni-paderborn.de:5000"]
}

Then you can pull the sessa image using:

docker pull project-group-search-extraction.cs.uni-paderborn.
de:5000/sessa:17122017 to check the image

And run the sessa docker using :

docker run -d --name sessa -p 7070:7070
project-group-search-extraction.cs.uni-paderborn.de:5000/sessa:17122017

Please let us know, if you have some issues while starting sessa,

*Thanks,*
*Guru*

**Comment by prasanthhs** [comment]
screen shot 2017-12-18 at 17 56 42
For your reference!

**Comment by RicardoUsbeck** [comment]
Okay, so here are two potential issues:
1) A microservice is always independent of other microservices, so please get rid of the connection between the webclient and the chatbot before the pull request is merged. https://martinfowler.com/articles/microservices.html 
2) SESSA can be successfully started from command line without docker. It is nice to know that there is a docker container and even a docker registry on the VM, however that was kind of not agreed upon. You start building your own shadow infrastructure which in the long term can lead to unrepeatable bugs and a very messy infrastructure. https://en.wikipedia.org/wiki/Shadow_IT

**Comment by prasanthhs** [comment]
@RicardoUsbeck  I have added some change and the issue doesn't occur on my PC now atleast(tried a few combinations and also a few retries). Can you check if its the case at your end ?

**Pull request merged**
