### PR TITLE
Extractor prototype

### PR DESCRIPTION
**Pull request by KHaack**
Hi,

now merged FOX & Spotlight.

Attention: FOX & fred are currently offline.

### CODE REVIEW

**Comment by RicardoUsbeck** [comment]
Adress clash in Fox
image

**Comment by KHaack** [comment]
Discoveryclient (Test Microservices): 2222
Fox: 2222
Fred: 2223
Spotlight: 2224
Webclient: 9090
Chatbot: 9191
Eureka: 1111

Please dont start the test microservice called "Discoveryclient". It is necessary.

**Comment by RicardoUsbeck** [comment]
Okay, so it is best that the Discroveryclient gets removed.

**Comment by KHaack** [comment]
ok

**Pull request merged**
